<a href="https://colab.research.google.com/github/ItsMeVenkatesh/Venkat/blob/main/DataPreprocessing_Assignment11_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Data.csv

**Step 1: Importing the libraries**

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

**Step 2: Importing dataset**

In [3]:
df = pd.read_csv("/content/Data.csv")

In [4]:
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [5]:
df.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [9]:
df.shape

(10, 4)

**Step 3: Handling the missing data**

In [11]:
df.isnull().sum()


Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

**Step 4: Encoding categorical data**

In [34]:
print(df.head())

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes


In [36]:
print(df['Country'].unique())
print(df['Purchased'].unique())

['France' 'Spain' 'Germany']
['No' 'Yes']


In [38]:
df['Country'].value_counts()
df['Purchased'].value_counts()


No     5
Yes    5
Name: Purchased, dtype: int64

In [39]:
one_hot_encoded_data = pd.get_dummies(df, columns = ['Purchased', 'Country'])
print(one_hot_encoded_data)


    Age   Salary  Purchased_No  Purchased_Yes  Country_France  \
0  44.0  72000.0             1              0               1   
1  27.0  48000.0             0              1               0   
2  30.0  54000.0             1              0               0   
3  38.0  61000.0             1              0               0   
4  40.0      NaN             0              1               0   
5  35.0  58000.0             0              1               1   
6   NaN  52000.0             1              0               0   
7  48.0  79000.0             0              1               1   
8  50.0  83000.0             1              0               0   
9  37.0  67000.0             0              1               1   

   Country_Germany  Country_Spain  
0                0              0  
1                0              1  
2                1              0  
3                0              1  
4                1              0  
5                0              0  
6                0              

**Step 5: Creating a dummy variable**

In [30]:
print (df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [31]:
pd.get_dummies(df)

Age   Salary  Country_France  Country_Germany  Country_Spain  \
0  44.0  72000.0               1                0              0   
1  27.0  48000.0               0                0              1   
2  30.0  54000.0               0                1              0   
3  38.0  61000.0               0                0              1   
4  40.0      NaN               0                1              0   
5  35.0  58000.0               1                0              0   
6   NaN  52000.0               0                0              1   
7  48.0  79000.0               1                0              0   
8  50.0  83000.0               0                1              0   
9  37.0  67000.0               1                0              0   

   Purchased_No  Purchased_Yes  
0             1              0  
1             0              1  
2             1              0  
3             1              0  
4             0              1  
5             0              1  
6             1              0  
7             0              1  
8             1              0  
9             0              1

**Step 6: Splitting the datasets into training sets and Test sets**

*   List item
*   List item



In [27]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [28]:
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.05, random_state=0)

**Step 7: Feature Scaling**

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import preprocessing

In [23]:
data_set = pd.read_csv('/content/Data.csv')
data_set.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [24]:
x = data_set.iloc[:, 1:3].values
print ("\nOriginal data values : \n",  x)


Original data values : 
 [[4.4e+01 7.2e+04]
 [2.7e+01 4.8e+04]
 [3.0e+01 5.4e+04]
 [3.8e+01 6.1e+04]
 [4.0e+01     nan]
 [3.5e+01 5.8e+04]
 [    nan 5.2e+04]
 [4.8e+01 7.9e+04]
 [5.0e+01 8.3e+04]
 [3.7e+01 6.7e+04]]


In [25]:
min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1))
x_after_min_max_scaler = min_max_scaler.fit_transform(x)
  
print ("\nAfter min max Scaling : \n", x_after_min_max_scaler)


After min max Scaling : 
 [[0.73913043 0.68571429]
 [0.         0.        ]
 [0.13043478 0.17142857]
 [0.47826087 0.37142857]
 [0.56521739        nan]
 [0.34782609 0.28571429]
 [       nan 0.11428571]
 [0.91304348 0.88571429]
 [1.         1.        ]
 [0.43478261 0.54285714]]


In [26]:
Standardisation = preprocessing.StandardScaler()
  
# Scaled feature
x_after_Standardisation = Standardisation.fit_transform(x)
  
print ("\nAfter Standardisation : \n", x_after_Standardisation)


After Standardisation : 
 [[ 0.71993143  0.71101276]
 [-1.62367514 -1.36437583]
 [-1.21009751 -0.84552869]
 [-0.10722383 -0.24020701]
 [ 0.16849459         nan]
 [-0.52080146 -0.49963059]
 [        nan -1.01847774]
 [ 1.27136827  1.31633443]
 [ 1.54708669  1.66223253]
 [-0.24508304  0.27864014]]
